version: '3'

vars:
  # GNU grep support depending on OS
  GREP_CMD:
    sh: |
      case "$(uname)" in
        Darwin*) echo ggrep ;;
        Linux*) echo grep ;;
      esac

tasks:
  ################# Development Tools ####################
  # Additional resources:
  # - https://buf.build/docs/installation
  # - https://buf.build/docs/lint/rules
  tools:
    desc: "Download tools required for development"
    cmds:
      - npm install
      - npx buf --version

  ################# Build Node.js Client ####################
  build:
    desc: "Builds the js files including declarations and CLI"
    cmds:
      - npm install
      - npm run build

  delete-binaries:
    desc: "Delete binary artifacts"
    cmds:
      - npm run clean

  proto-update:
    desc: "Updates the proto files and regenerates JS stubs"
    cmds:
      - git submodule update --remote protobuf/
      - task: proto

  proto:
    desc: "Generates JS stubs from proto files"
    cmds:
      - npx buf generate

  ################# Continuous Improvement Tasks ####################
  npm-ci:
    desc: "Applies npm ci to install dependencies based on package-lock.json"
    env:
      HUSKY: 0
    cmds:
      - npm ci

  format:
    desc: "Apply formatting rules to Node.js code"
    cmds:
      - npm run format

  lint:
    desc: "Apply linting to Node.js code"
    cmds:
      - npm run lint

  unit-test:
    deps: [build]
    desc: "Run unit-tests"
    cmds:
      - npm run test

  vulnerability-check:
    desc: "Run vulnerability check"
    cmds:
      - npm audit

  ci:
    desc: "Runs continuous integration checks on source code"
    cmds:
    - task: npm-ci
    - task: format
    - task: lint
    - task: unit-test
    - task: vulnerability-check
