version: '3'

vars:
  PROTOBUF_VERSION: "32.1"
  # GNU grep support depending on OS
  GREP_CMD:
    sh: |
      case "$(uname)" in
        Darwin*) echo ggrep ;;
        Linux*) echo grep ;;
      esac

tasks:
  ################# Development Tools ####################
  # Additional resources:
  # - https://protobuf.dev/getting-started/
  # - https://protobuf.dev/installation/
  tools:
    desc: "Download tools required for development"
    deps: [install-protobuf-compiler]
    cmds:
      - protoc --version

  # Public task to install the pre-built protobuf compiler depending on the architecture
  install-protobuf-compiler:
    desc: "Download and install pre-built protobuf compiler"
    cmds:
      - task: install-protobuf-compiler-linux-amd64
      - task: install-protobuf-compiler-darwin

  install-protobuf-compiler-linux-amd64:
    desc: "Download and install pre-built protobuf compiler for Linux"
    internal: true
    platforms: ["linux/amd64"]
    cmds:
      # Create temporary download folder
      - mkdir tmp-download
      # Download specified version
      - cd tmp-download && curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v{{.PROTOBUF_VERSION}}/protoc-{{.PROTOBUF_VERSION}}-linux-x86_64.zip
      # Unzip download
      - cd tmp-download && unzip protoc-{{.PROTOBUF_VERSION}}-linux-x86_64.zip -d $HOME/.local/share/protobuf/
      # Remove temporary download folder
      - rm -rf tmp-download
      # Add path to .bashrc if it does not already exists
      - grep -qx 'export PATH="$PATH:$HOME/.local/share/protobuf/bin"' ~/.bashrc || echo 'export PATH="$PATH:$HOME/.local/share/protobuf/bin"' >> ~/.bashrc
      # Reload .bashrc
      - source $HOME/.bashrc

  install-protobuf-compiler-darwin:
    desc: "Download and install protobuf compiler for Apple/macOS"
    internal: true
    platforms: ["darwin"]
    cmds:
      - brew install protobuf

  ################# Build Node.js Client ####################
  build:
    desc: "Builds the js files including declarations and CLI"
    cmds:
      - npm install
      - npm run build

  delete-binaries:
    desc: "Delete binary artifacts"
    cmds:
      - npm run clean

  proto:
    desc: "Generates JS stubs from proto files"
    cmds:
      - git submodule update --init --recursive --remote
      - protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./src/lib/proto -I ./protobuf/ messages.proto
      - protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./src/lib/proto/third_party/grpc/health/v1/ -I ./protobuf/third_party/grpc/health/v1/ health.proto

  ################# Continuous Improvement Tasks ####################
  format:
    desc: "Apply formatting rules to Node.js code"
    cmds:
      - npm run format

  lint:
    desc: "Apply linting to Node.js code"
    cmds:
      - npm run lint

  unit-test:
    desc: "Run unit-tests"
    cmds:
      - npm run test

  vulnerability-check:
    desc: "Run vulnerability check"
    cmds:
      - npm audit

  ci:
    desc: "Runs continuous integration checks on source code"
    cmds:
    - task: format
    - task: lint
    - task: unit-test
    - task: vulnerability-check
