// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: messages.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
export const protobufPackage = 'CryptoBroker';
/** Output formats */
export var HashOutputFormat;
(function (HashOutputFormat) {
  HashOutputFormat[(HashOutputFormat['HEX'] = 0)] = 'HEX';
  HashOutputFormat[(HashOutputFormat['RAW'] = 1)] = 'RAW';
  HashOutputFormat[(HashOutputFormat['UNRECOGNIZED'] = -1)] = 'UNRECOGNIZED';
})(HashOutputFormat || (HashOutputFormat = {}));
export function hashOutputFormatFromJSON(object) {
  switch (object) {
    case 0:
    case 'HEX':
      return HashOutputFormat.HEX;
    case 1:
    case 'RAW':
      return HashOutputFormat.RAW;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return HashOutputFormat.UNRECOGNIZED;
  }
}
export function hashOutputFormatToJSON(object) {
  switch (object) {
    case HashOutputFormat.HEX:
      return 'HEX';
    case HashOutputFormat.RAW:
      return 'RAW';
    case HashOutputFormat.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED';
  }
}
export var SignOutputFormat;
(function (SignOutputFormat) {
  SignOutputFormat[(SignOutputFormat['DER'] = 0)] = 'DER';
  SignOutputFormat[(SignOutputFormat['PEM'] = 1)] = 'PEM';
  SignOutputFormat[(SignOutputFormat['UNRECOGNIZED'] = -1)] = 'UNRECOGNIZED';
})(SignOutputFormat || (SignOutputFormat = {}));
export function signOutputFormatFromJSON(object) {
  switch (object) {
    case 0:
    case 'DER':
      return SignOutputFormat.DER;
    case 1:
    case 'PEM':
      return SignOutputFormat.PEM;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return SignOutputFormat.UNRECOGNIZED;
  }
}
export function signOutputFormatToJSON(object) {
  switch (object) {
    case SignOutputFormat.DER:
      return 'DER';
    case SignOutputFormat.PEM:
      return 'PEM';
    case SignOutputFormat.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED';
  }
}
/** Single source of truth for gRPC message size limits, applied as transport options in the server and clients. */
export var MessageSizeLimit;
(function (MessageSizeLimit) {
  MessageSizeLimit[(MessageSizeLimit['MESSAGE_SIZE_LIMIT_UNSPECIFIED'] = 0)] =
    'MESSAGE_SIZE_LIMIT_UNSPECIFIED';
  /** MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES - Max request accepted from client to server (2 MiB). */
  MessageSizeLimit[
    (MessageSizeLimit['MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES'] = 2097152)
  ] = 'MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES';
  /** MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES - Max response returned from server to client (1 MiB). */
  MessageSizeLimit[
    (MessageSizeLimit['MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES'] = 1048576)
  ] = 'MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES';
  MessageSizeLimit[(MessageSizeLimit['UNRECOGNIZED'] = -1)] = 'UNRECOGNIZED';
})(MessageSizeLimit || (MessageSizeLimit = {}));
export function messageSizeLimitFromJSON(object) {
  switch (object) {
    case 0:
    case 'MESSAGE_SIZE_LIMIT_UNSPECIFIED':
      return MessageSizeLimit.MESSAGE_SIZE_LIMIT_UNSPECIFIED;
    case 2097152:
    case 'MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES':
      return MessageSizeLimit.MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES;
    case 1048576:
    case 'MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES':
      return MessageSizeLimit.MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return MessageSizeLimit.UNRECOGNIZED;
  }
}
export function messageSizeLimitToJSON(object) {
  switch (object) {
    case MessageSizeLimit.MESSAGE_SIZE_LIMIT_UNSPECIFIED:
      return 'MESSAGE_SIZE_LIMIT_UNSPECIFIED';
    case MessageSizeLimit.MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES:
      return 'MESSAGE_SIZE_LIMIT_MAX_REQUEST_BYTES';
    case MessageSizeLimit.MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES:
      return 'MESSAGE_SIZE_LIMIT_MAX_RESPONSE_BYTES';
    case MessageSizeLimit.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED';
  }
}
function createBaseMetadata() {
  return { id: '', deprecation: undefined, traceContext: undefined };
}
export const Metadata = {
  encode(message, writer = new BinaryWriter()) {
    if (message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.deprecation !== undefined) {
      DeprecationWarning.encode(
        message.deprecation,
        writer.uint32(18).fork(),
      ).join();
    }
    if (message.traceContext !== undefined) {
      TraceContext.encode(
        message.traceContext,
        writer.uint32(26).fork(),
      ).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.deprecation = DeprecationWarning.decode(
            reader,
            reader.uint32(),
          );
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.traceContext = TraceContext.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : '',
      deprecation: isSet(object.deprecation)
        ? DeprecationWarning.fromJSON(object.deprecation)
        : undefined,
      traceContext: isSet(object.traceContext)
        ? TraceContext.fromJSON(object.traceContext)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.id !== '') {
      obj.id = message.id;
    }
    if (message.deprecation !== undefined) {
      obj.deprecation = DeprecationWarning.toJSON(message.deprecation);
    }
    if (message.traceContext !== undefined) {
      obj.traceContext = TraceContext.toJSON(message.traceContext);
    }
    return obj;
  },
  create(base) {
    return Metadata.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseMetadata();
    message.id = object.id ?? '';
    message.deprecation =
      object.deprecation !== undefined && object.deprecation !== null
        ? DeprecationWarning.fromPartial(object.deprecation)
        : undefined;
    message.traceContext =
      object.traceContext !== undefined && object.traceContext !== null
        ? TraceContext.fromPartial(object.traceContext)
        : undefined;
    return message;
  },
};
function createBaseCryptoDescriptor() {
  return { profile: '', operation: '', algorithm: '' };
}
export const CryptoDescriptor = {
  encode(message, writer = new BinaryWriter()) {
    if (message.profile !== '') {
      writer.uint32(10).string(message.profile);
    }
    if (message.operation !== '') {
      writer.uint32(18).string(message.operation);
    }
    if (message.algorithm !== '') {
      writer.uint32(26).string(message.algorithm);
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCryptoDescriptor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.profile = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.operation = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.algorithm = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      profile: isSet(object.profile) ? globalThis.String(object.profile) : '',
      operation: isSet(object.operation)
        ? globalThis.String(object.operation)
        : '',
      algorithm: isSet(object.algorithm)
        ? globalThis.String(object.algorithm)
        : '',
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.profile !== '') {
      obj.profile = message.profile;
    }
    if (message.operation !== '') {
      obj.operation = message.operation;
    }
    if (message.algorithm !== '') {
      obj.algorithm = message.algorithm;
    }
    return obj;
  },
  create(base) {
    return CryptoDescriptor.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseCryptoDescriptor();
    message.profile = object.profile ?? '';
    message.operation = object.operation ?? '';
    message.algorithm = object.algorithm ?? '';
    return message;
  },
};
function createBaseDeprecationWarning() {
  return {
    profile: '',
    replacedBy: undefined,
    deprecatedSince: undefined,
    removeAfter: undefined,
    reason: undefined,
  };
}
export const DeprecationWarning = {
  encode(message, writer = new BinaryWriter()) {
    if (message.profile !== '') {
      writer.uint32(10).string(message.profile);
    }
    if (message.replacedBy !== undefined) {
      writer.uint32(18).string(message.replacedBy);
    }
    if (message.deprecatedSince !== undefined) {
      writer.uint32(26).string(message.deprecatedSince);
    }
    if (message.removeAfter !== undefined) {
      writer.uint32(34).string(message.removeAfter);
    }
    if (message.reason !== undefined) {
      writer.uint32(42).string(message.reason);
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeprecationWarning();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.profile = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.replacedBy = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.deprecatedSince = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }
          message.removeAfter = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }
          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      profile: isSet(object.profile) ? globalThis.String(object.profile) : '',
      replacedBy: isSet(object.replacedBy)
        ? globalThis.String(object.replacedBy)
        : undefined,
      deprecatedSince: isSet(object.deprecatedSince)
        ? globalThis.String(object.deprecatedSince)
        : undefined,
      removeAfter: isSet(object.removeAfter)
        ? globalThis.String(object.removeAfter)
        : undefined,
      reason: isSet(object.reason)
        ? globalThis.String(object.reason)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.profile !== '') {
      obj.profile = message.profile;
    }
    if (message.replacedBy !== undefined) {
      obj.replacedBy = message.replacedBy;
    }
    if (message.deprecatedSince !== undefined) {
      obj.deprecatedSince = message.deprecatedSince;
    }
    if (message.removeAfter !== undefined) {
      obj.removeAfter = message.removeAfter;
    }
    if (message.reason !== undefined) {
      obj.reason = message.reason;
    }
    return obj;
  },
  create(base) {
    return DeprecationWarning.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseDeprecationWarning();
    message.profile = object.profile ?? '';
    message.replacedBy = object.replacedBy ?? undefined;
    message.deprecatedSince = object.deprecatedSince ?? undefined;
    message.removeAfter = object.removeAfter ?? undefined;
    message.reason = object.reason ?? undefined;
    return message;
  },
};
function createBaseTraceContext() {
  return {
    traceId: '',
    spanId: '',
    traceFlags: '',
    traceState: '',
    correlationId: '',
  };
}
export const TraceContext = {
  encode(message, writer = new BinaryWriter()) {
    if (message.traceId !== '') {
      writer.uint32(10).string(message.traceId);
    }
    if (message.spanId !== '') {
      writer.uint32(18).string(message.spanId);
    }
    if (message.traceFlags !== '') {
      writer.uint32(26).string(message.traceFlags);
    }
    if (message.traceState !== '') {
      writer.uint32(34).string(message.traceState);
    }
    if (message.correlationId !== '') {
      writer.uint32(42).string(message.correlationId);
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTraceContext();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.traceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.spanId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.traceFlags = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }
          message.traceState = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }
          message.correlationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      traceId: isSet(object.traceId) ? globalThis.String(object.traceId) : '',
      spanId: isSet(object.spanId) ? globalThis.String(object.spanId) : '',
      traceFlags: isSet(object.traceFlags)
        ? globalThis.String(object.traceFlags)
        : '',
      traceState: isSet(object.traceState)
        ? globalThis.String(object.traceState)
        : '',
      correlationId: isSet(object.correlationId)
        ? globalThis.String(object.correlationId)
        : '',
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.traceId !== '') {
      obj.traceId = message.traceId;
    }
    if (message.spanId !== '') {
      obj.spanId = message.spanId;
    }
    if (message.traceFlags !== '') {
      obj.traceFlags = message.traceFlags;
    }
    if (message.traceState !== '') {
      obj.traceState = message.traceState;
    }
    if (message.correlationId !== '') {
      obj.correlationId = message.correlationId;
    }
    return obj;
  },
  create(base) {
    return TraceContext.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseTraceContext();
    message.traceId = object.traceId ?? '';
    message.spanId = object.spanId ?? '';
    message.traceFlags = object.traceFlags ?? '';
    message.traceState = object.traceState ?? '';
    message.correlationId = object.correlationId ?? '';
    return message;
  },
};
function createBaseKeySource() {
  return { keyId: undefined, rawKey: undefined };
}
export const KeySource = {
  encode(message, writer = new BinaryWriter()) {
    if (message.keyId !== undefined) {
      writer.uint32(10).string(message.keyId);
    }
    if (message.rawKey !== undefined) {
      writer.uint32(18).bytes(message.rawKey);
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeySource();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.keyId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.rawKey = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      keyId: isSet(object.keyId) ? globalThis.String(object.keyId) : undefined,
      rawKey: isSet(object.rawKey) ? bytesFromBase64(object.rawKey) : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.keyId !== undefined) {
      obj.keyId = message.keyId;
    }
    if (message.rawKey !== undefined) {
      obj.rawKey = base64FromBytes(message.rawKey);
    }
    return obj;
  },
  create(base) {
    return KeySource.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseKeySource();
    message.keyId = object.keyId ?? undefined;
    message.rawKey = object.rawKey ?? undefined;
    return message;
  },
};
function createBaseEncryptMetadata() {
  return { nonce: new Uint8Array(0), aad: undefined };
}
export const EncryptMetadata = {
  encode(message, writer = new BinaryWriter()) {
    if (message.nonce.length !== 0) {
      writer.uint32(10).bytes(message.nonce);
    }
    if (message.aad !== undefined) {
      writer.uint32(18).bytes(message.aad);
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEncryptMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.nonce = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.aad = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      nonce: isSet(object.nonce)
        ? bytesFromBase64(object.nonce)
        : new Uint8Array(0),
      aad: isSet(object.aad) ? bytesFromBase64(object.aad) : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.nonce.length !== 0) {
      obj.nonce = base64FromBytes(message.nonce);
    }
    if (message.aad !== undefined) {
      obj.aad = base64FromBytes(message.aad);
    }
    return obj;
  },
  create(base) {
    return EncryptMetadata.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseEncryptMetadata();
    message.nonce = object.nonce ?? new Uint8Array(0);
    message.aad = object.aad ?? undefined;
    return message;
  },
};
function createBaseCipherMetadata() {
  return {
    keyId: undefined,
    nonce: new Uint8Array(0),
    aad: undefined,
    tag: undefined,
  };
}
export const CipherMetadata = {
  encode(message, writer = new BinaryWriter()) {
    if (message.keyId !== undefined) {
      writer.uint32(10).string(message.keyId);
    }
    if (message.nonce.length !== 0) {
      writer.uint32(18).bytes(message.nonce);
    }
    if (message.aad !== undefined) {
      writer.uint32(26).bytes(message.aad);
    }
    if (message.tag !== undefined) {
      writer.uint32(34).bytes(message.tag);
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCipherMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.keyId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.nonce = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.aad = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }
          message.tag = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      keyId: isSet(object.keyId) ? globalThis.String(object.keyId) : undefined,
      nonce: isSet(object.nonce)
        ? bytesFromBase64(object.nonce)
        : new Uint8Array(0),
      aad: isSet(object.aad) ? bytesFromBase64(object.aad) : undefined,
      tag: isSet(object.tag) ? bytesFromBase64(object.tag) : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.keyId !== undefined) {
      obj.keyId = message.keyId;
    }
    if (message.nonce.length !== 0) {
      obj.nonce = base64FromBytes(message.nonce);
    }
    if (message.aad !== undefined) {
      obj.aad = base64FromBytes(message.aad);
    }
    if (message.tag !== undefined) {
      obj.tag = base64FromBytes(message.tag);
    }
    return obj;
  },
  create(base) {
    return CipherMetadata.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseCipherMetadata();
    message.keyId = object.keyId ?? undefined;
    message.nonce = object.nonce ?? new Uint8Array(0);
    message.aad = object.aad ?? undefined;
    message.tag = object.tag ?? undefined;
    return message;
  },
};
function createBaseDecryptMetadata() {
  return { nonce: new Uint8Array(0), aad: undefined, tag: undefined };
}
export const DecryptMetadata = {
  encode(message, writer = new BinaryWriter()) {
    if (message.nonce.length !== 0) {
      writer.uint32(10).bytes(message.nonce);
    }
    if (message.aad !== undefined) {
      writer.uint32(18).bytes(message.aad);
    }
    if (message.tag !== undefined) {
      writer.uint32(26).bytes(message.tag);
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDecryptMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.nonce = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.aad = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.tag = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      nonce: isSet(object.nonce)
        ? bytesFromBase64(object.nonce)
        : new Uint8Array(0),
      aad: isSet(object.aad) ? bytesFromBase64(object.aad) : undefined,
      tag: isSet(object.tag) ? bytesFromBase64(object.tag) : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.nonce.length !== 0) {
      obj.nonce = base64FromBytes(message.nonce);
    }
    if (message.aad !== undefined) {
      obj.aad = base64FromBytes(message.aad);
    }
    if (message.tag !== undefined) {
      obj.tag = base64FromBytes(message.tag);
    }
    return obj;
  },
  create(base) {
    return DecryptMetadata.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseDecryptMetadata();
    message.nonce = object.nonce ?? new Uint8Array(0);
    message.aad = object.aad ?? undefined;
    message.tag = object.tag ?? undefined;
    return message;
  },
};
function createBaseHashDataRequest() {
  return {
    profile: '',
    input: new Uint8Array(0),
    metadata: undefined,
    outputFormat: 0,
  };
}
export const HashDataRequest = {
  encode(message, writer = new BinaryWriter()) {
    if (message.profile !== '') {
      writer.uint32(10).string(message.profile);
    }
    if (message.input.length !== 0) {
      writer.uint32(18).bytes(message.input);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(26).fork()).join();
    }
    if (message.outputFormat !== 0) {
      writer.uint32(32).int32(message.outputFormat);
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHashDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.profile = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.input = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }
          message.outputFormat = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      profile: isSet(object.profile) ? globalThis.String(object.profile) : '',
      input: isSet(object.input)
        ? bytesFromBase64(object.input)
        : new Uint8Array(0),
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
      outputFormat: isSet(object.outputFormat)
        ? hashOutputFormatFromJSON(object.outputFormat)
        : 0,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.profile !== '') {
      obj.profile = message.profile;
    }
    if (message.input.length !== 0) {
      obj.input = base64FromBytes(message.input);
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    if (message.outputFormat !== 0) {
      obj.outputFormat = hashOutputFormatToJSON(message.outputFormat);
    }
    return obj;
  },
  create(base) {
    return HashDataRequest.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseHashDataRequest();
    message.profile = object.profile ?? '';
    message.input = object.input ?? new Uint8Array(0);
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    message.outputFormat = object.outputFormat ?? 0;
    return message;
  },
};
function createBaseHashDataResponse() {
  return {
    hashAlgorithm: '',
    metadata: undefined,
    hashValueHex: undefined,
    hashValueRaw: undefined,
    descriptor: undefined,
  };
}
export const HashDataResponse = {
  encode(message, writer = new BinaryWriter()) {
    if (message.hashAlgorithm !== '') {
      writer.uint32(18).string(message.hashAlgorithm);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(26).fork()).join();
    }
    if (message.hashValueHex !== undefined) {
      writer.uint32(34).string(message.hashValueHex);
    }
    if (message.hashValueRaw !== undefined) {
      writer.uint32(42).bytes(message.hashValueRaw);
    }
    if (message.descriptor !== undefined) {
      CryptoDescriptor.encode(
        message.descriptor,
        writer.uint32(50).fork(),
      ).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHashDataResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.hashAlgorithm = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }
          message.hashValueHex = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }
          message.hashValueRaw = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }
          message.descriptor = CryptoDescriptor.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      hashAlgorithm: isSet(object.hashAlgorithm)
        ? globalThis.String(object.hashAlgorithm)
        : '',
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
      hashValueHex: isSet(object.hashValueHex)
        ? globalThis.String(object.hashValueHex)
        : undefined,
      hashValueRaw: isSet(object.hashValueRaw)
        ? bytesFromBase64(object.hashValueRaw)
        : undefined,
      descriptor: isSet(object.descriptor)
        ? CryptoDescriptor.fromJSON(object.descriptor)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.hashAlgorithm !== '') {
      obj.hashAlgorithm = message.hashAlgorithm;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    if (message.hashValueHex !== undefined) {
      obj.hashValueHex = message.hashValueHex;
    }
    if (message.hashValueRaw !== undefined) {
      obj.hashValueRaw = base64FromBytes(message.hashValueRaw);
    }
    if (message.descriptor !== undefined) {
      obj.descriptor = CryptoDescriptor.toJSON(message.descriptor);
    }
    return obj;
  },
  create(base) {
    return HashDataResponse.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseHashDataResponse();
    message.hashAlgorithm = object.hashAlgorithm ?? '';
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    message.hashValueHex = object.hashValueHex ?? undefined;
    message.hashValueRaw = object.hashValueRaw ?? undefined;
    message.descriptor =
      object.descriptor !== undefined && object.descriptor !== null
        ? CryptoDescriptor.fromPartial(object.descriptor)
        : undefined;
    return message;
  },
};
function createBaseSignCertificateRequest() {
  return {
    profile: '',
    csr: '',
    caPrivateKey: '',
    caCert: '',
    metadata: undefined,
    validNotBefore: undefined,
    validNotAfter: undefined,
    subject: undefined,
    crlDistributionPoints: [],
    outputFormat: 0,
  };
}
export const SignCertificateRequest = {
  encode(message, writer = new BinaryWriter()) {
    if (message.profile !== '') {
      writer.uint32(10).string(message.profile);
    }
    if (message.csr !== '') {
      writer.uint32(18).string(message.csr);
    }
    if (message.caPrivateKey !== '') {
      writer.uint32(26).string(message.caPrivateKey);
    }
    if (message.caCert !== '') {
      writer.uint32(34).string(message.caCert);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(42).fork()).join();
    }
    if (message.validNotBefore !== undefined) {
      if (
        BigInt.asUintN(64, message.validNotBefore) !== message.validNotBefore
      ) {
        throw new globalThis.Error(
          'value provided for field message.validNotBefore of type uint64 too large',
        );
      }
      writer.uint32(48).uint64(message.validNotBefore);
    }
    if (message.validNotAfter !== undefined) {
      if (BigInt.asUintN(64, message.validNotAfter) !== message.validNotAfter) {
        throw new globalThis.Error(
          'value provided for field message.validNotAfter of type uint64 too large',
        );
      }
      writer.uint32(56).uint64(message.validNotAfter);
    }
    if (message.subject !== undefined) {
      writer.uint32(66).string(message.subject);
    }
    for (const v of message.crlDistributionPoints) {
      writer.uint32(74).string(v);
    }
    if (message.outputFormat !== 0) {
      writer.uint32(80).int32(message.outputFormat);
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignCertificateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.profile = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.csr = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.caPrivateKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }
          message.caCert = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }
          message.validNotBefore = reader.uint64();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }
          message.validNotAfter = reader.uint64();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }
          message.subject = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }
          message.crlDistributionPoints.push(reader.string());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }
          message.outputFormat = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      profile: isSet(object.profile) ? globalThis.String(object.profile) : '',
      csr: isSet(object.csr) ? globalThis.String(object.csr) : '',
      caPrivateKey: isSet(object.caPrivateKey)
        ? globalThis.String(object.caPrivateKey)
        : '',
      caCert: isSet(object.caCert) ? globalThis.String(object.caCert) : '',
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
      validNotBefore: isSet(object.validNotBefore)
        ? BigInt(object.validNotBefore)
        : undefined,
      validNotAfter: isSet(object.validNotAfter)
        ? BigInt(object.validNotAfter)
        : undefined,
      subject: isSet(object.subject)
        ? globalThis.String(object.subject)
        : undefined,
      crlDistributionPoints: globalThis.Array.isArray(
        object?.crlDistributionPoints,
      )
        ? object.crlDistributionPoints.map((e) => globalThis.String(e))
        : [],
      outputFormat: isSet(object.outputFormat)
        ? signOutputFormatFromJSON(object.outputFormat)
        : 0,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.profile !== '') {
      obj.profile = message.profile;
    }
    if (message.csr !== '') {
      obj.csr = message.csr;
    }
    if (message.caPrivateKey !== '') {
      obj.caPrivateKey = message.caPrivateKey;
    }
    if (message.caCert !== '') {
      obj.caCert = message.caCert;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    if (message.validNotBefore !== undefined) {
      obj.validNotBefore = message.validNotBefore.toString();
    }
    if (message.validNotAfter !== undefined) {
      obj.validNotAfter = message.validNotAfter.toString();
    }
    if (message.subject !== undefined) {
      obj.subject = message.subject;
    }
    if (message.crlDistributionPoints?.length) {
      obj.crlDistributionPoints = message.crlDistributionPoints;
    }
    if (message.outputFormat !== 0) {
      obj.outputFormat = signOutputFormatToJSON(message.outputFormat);
    }
    return obj;
  },
  create(base) {
    return SignCertificateRequest.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseSignCertificateRequest();
    message.profile = object.profile ?? '';
    message.csr = object.csr ?? '';
    message.caPrivateKey = object.caPrivateKey ?? '';
    message.caCert = object.caCert ?? '';
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    message.validNotBefore =
      object.validNotBefore !== undefined && object.validNotBefore !== null
        ? BigInt(object.validNotBefore)
        : undefined;
    message.validNotAfter =
      object.validNotAfter !== undefined && object.validNotAfter !== null
        ? BigInt(object.validNotAfter)
        : undefined;
    message.subject = object.subject ?? undefined;
    message.crlDistributionPoints =
      object.crlDistributionPoints?.map((e) => e) || [];
    message.outputFormat = object.outputFormat ?? 0;
    return message;
  },
};
function createBaseSignCertificateResponse() {
  return {
    metadata: undefined,
    pem: undefined,
    der: undefined,
    descriptor: undefined,
  };
}
export const SignCertificateResponse = {
  encode(message, writer = new BinaryWriter()) {
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(18).fork()).join();
    }
    if (message.pem !== undefined) {
      writer.uint32(26).string(message.pem);
    }
    if (message.der !== undefined) {
      writer.uint32(34).bytes(message.der);
    }
    if (message.descriptor !== undefined) {
      CryptoDescriptor.encode(
        message.descriptor,
        writer.uint32(42).fork(),
      ).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignCertificateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.pem = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }
          message.der = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }
          message.descriptor = CryptoDescriptor.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
      pem: isSet(object.pem) ? globalThis.String(object.pem) : undefined,
      der: isSet(object.der) ? bytesFromBase64(object.der) : undefined,
      descriptor: isSet(object.descriptor)
        ? CryptoDescriptor.fromJSON(object.descriptor)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    if (message.pem !== undefined) {
      obj.pem = message.pem;
    }
    if (message.der !== undefined) {
      obj.der = base64FromBytes(message.der);
    }
    if (message.descriptor !== undefined) {
      obj.descriptor = CryptoDescriptor.toJSON(message.descriptor);
    }
    return obj;
  },
  create(base) {
    return SignCertificateResponse.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseSignCertificateResponse();
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    message.pem = object.pem ?? undefined;
    message.der = object.der ?? undefined;
    message.descriptor =
      object.descriptor !== undefined && object.descriptor !== null
        ? CryptoDescriptor.fromPartial(object.descriptor)
        : undefined;
    return message;
  },
};
function createBaseEncryptDataRequest() {
  return {
    profile: '',
    keySource: undefined,
    plaintext: new Uint8Array(0),
    encryptMetadata: undefined,
    metadata: undefined,
  };
}
export const EncryptDataRequest = {
  encode(message, writer = new BinaryWriter()) {
    if (message.profile !== '') {
      writer.uint32(10).string(message.profile);
    }
    if (message.keySource !== undefined) {
      KeySource.encode(message.keySource, writer.uint32(18).fork()).join();
    }
    if (message.plaintext.length !== 0) {
      writer.uint32(26).bytes(message.plaintext);
    }
    if (message.encryptMetadata !== undefined) {
      EncryptMetadata.encode(
        message.encryptMetadata,
        writer.uint32(34).fork(),
      ).join();
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(42).fork()).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEncryptDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.profile = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.keySource = KeySource.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.plaintext = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }
          message.encryptMetadata = EncryptMetadata.decode(
            reader,
            reader.uint32(),
          );
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      profile: isSet(object.profile) ? globalThis.String(object.profile) : '',
      keySource: isSet(object.keySource)
        ? KeySource.fromJSON(object.keySource)
        : undefined,
      plaintext: isSet(object.plaintext)
        ? bytesFromBase64(object.plaintext)
        : new Uint8Array(0),
      encryptMetadata: isSet(object.encryptMetadata)
        ? EncryptMetadata.fromJSON(object.encryptMetadata)
        : undefined,
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.profile !== '') {
      obj.profile = message.profile;
    }
    if (message.keySource !== undefined) {
      obj.keySource = KeySource.toJSON(message.keySource);
    }
    if (message.plaintext.length !== 0) {
      obj.plaintext = base64FromBytes(message.plaintext);
    }
    if (message.encryptMetadata !== undefined) {
      obj.encryptMetadata = EncryptMetadata.toJSON(message.encryptMetadata);
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },
  create(base) {
    return EncryptDataRequest.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseEncryptDataRequest();
    message.profile = object.profile ?? '';
    message.keySource =
      object.keySource !== undefined && object.keySource !== null
        ? KeySource.fromPartial(object.keySource)
        : undefined;
    message.plaintext = object.plaintext ?? new Uint8Array(0);
    message.encryptMetadata =
      object.encryptMetadata !== undefined && object.encryptMetadata !== null
        ? EncryptMetadata.fromPartial(object.encryptMetadata)
        : undefined;
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    return message;
  },
};
function createBaseEncryptDataResponse() {
  return {
    ciphertext: new Uint8Array(0),
    cipherMetadata: undefined,
    metadata: undefined,
    descriptor: undefined,
  };
}
export const EncryptDataResponse = {
  encode(message, writer = new BinaryWriter()) {
    if (message.ciphertext.length !== 0) {
      writer.uint32(10).bytes(message.ciphertext);
    }
    if (message.cipherMetadata !== undefined) {
      CipherMetadata.encode(
        message.cipherMetadata,
        writer.uint32(18).fork(),
      ).join();
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(26).fork()).join();
    }
    if (message.descriptor !== undefined) {
      CryptoDescriptor.encode(
        message.descriptor,
        writer.uint32(34).fork(),
      ).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEncryptDataResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.ciphertext = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.cipherMetadata = CipherMetadata.decode(
            reader,
            reader.uint32(),
          );
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }
          message.descriptor = CryptoDescriptor.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      ciphertext: isSet(object.ciphertext)
        ? bytesFromBase64(object.ciphertext)
        : new Uint8Array(0),
      cipherMetadata: isSet(object.cipherMetadata)
        ? CipherMetadata.fromJSON(object.cipherMetadata)
        : undefined,
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
      descriptor: isSet(object.descriptor)
        ? CryptoDescriptor.fromJSON(object.descriptor)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.ciphertext.length !== 0) {
      obj.ciphertext = base64FromBytes(message.ciphertext);
    }
    if (message.cipherMetadata !== undefined) {
      obj.cipherMetadata = CipherMetadata.toJSON(message.cipherMetadata);
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    if (message.descriptor !== undefined) {
      obj.descriptor = CryptoDescriptor.toJSON(message.descriptor);
    }
    return obj;
  },
  create(base) {
    return EncryptDataResponse.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseEncryptDataResponse();
    message.ciphertext = object.ciphertext ?? new Uint8Array(0);
    message.cipherMetadata =
      object.cipherMetadata !== undefined && object.cipherMetadata !== null
        ? CipherMetadata.fromPartial(object.cipherMetadata)
        : undefined;
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    message.descriptor =
      object.descriptor !== undefined && object.descriptor !== null
        ? CryptoDescriptor.fromPartial(object.descriptor)
        : undefined;
    return message;
  },
};
function createBaseDecryptDataRequest() {
  return {
    profile: '',
    keySource: undefined,
    ciphertext: new Uint8Array(0),
    decryptMetadata: undefined,
    metadata: undefined,
  };
}
export const DecryptDataRequest = {
  encode(message, writer = new BinaryWriter()) {
    if (message.profile !== '') {
      writer.uint32(10).string(message.profile);
    }
    if (message.keySource !== undefined) {
      KeySource.encode(message.keySource, writer.uint32(18).fork()).join();
    }
    if (message.ciphertext.length !== 0) {
      writer.uint32(26).bytes(message.ciphertext);
    }
    if (message.decryptMetadata !== undefined) {
      DecryptMetadata.encode(
        message.decryptMetadata,
        writer.uint32(34).fork(),
      ).join();
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(42).fork()).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDecryptDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.profile = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.keySource = KeySource.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }
          message.ciphertext = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }
          message.decryptMetadata = DecryptMetadata.decode(
            reader,
            reader.uint32(),
          );
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      profile: isSet(object.profile) ? globalThis.String(object.profile) : '',
      keySource: isSet(object.keySource)
        ? KeySource.fromJSON(object.keySource)
        : undefined,
      ciphertext: isSet(object.ciphertext)
        ? bytesFromBase64(object.ciphertext)
        : new Uint8Array(0),
      decryptMetadata: isSet(object.decryptMetadata)
        ? DecryptMetadata.fromJSON(object.decryptMetadata)
        : undefined,
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.profile !== '') {
      obj.profile = message.profile;
    }
    if (message.keySource !== undefined) {
      obj.keySource = KeySource.toJSON(message.keySource);
    }
    if (message.ciphertext.length !== 0) {
      obj.ciphertext = base64FromBytes(message.ciphertext);
    }
    if (message.decryptMetadata !== undefined) {
      obj.decryptMetadata = DecryptMetadata.toJSON(message.decryptMetadata);
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },
  create(base) {
    return DecryptDataRequest.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseDecryptDataRequest();
    message.profile = object.profile ?? '';
    message.keySource =
      object.keySource !== undefined && object.keySource !== null
        ? KeySource.fromPartial(object.keySource)
        : undefined;
    message.ciphertext = object.ciphertext ?? new Uint8Array(0);
    message.decryptMetadata =
      object.decryptMetadata !== undefined && object.decryptMetadata !== null
        ? DecryptMetadata.fromPartial(object.decryptMetadata)
        : undefined;
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    return message;
  },
};
function createBaseDecryptDataResponse() {
  return { plaintext: new Uint8Array(0), metadata: undefined };
}
export const DecryptDataResponse = {
  encode(message, writer = new BinaryWriter()) {
    if (message.plaintext.length !== 0) {
      writer.uint32(10).bytes(message.plaintext);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(18).fork()).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDecryptDataResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.plaintext = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      plaintext: isSet(object.plaintext)
        ? bytesFromBase64(object.plaintext)
        : new Uint8Array(0),
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.plaintext.length !== 0) {
      obj.plaintext = base64FromBytes(message.plaintext);
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },
  create(base) {
    return DecryptDataResponse.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseDecryptDataResponse();
    message.plaintext = object.plaintext ?? new Uint8Array(0);
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    return message;
  },
};
function createBaseBenchmarkRequest() {
  return { metadata: undefined };
}
export const BenchmarkRequest = {
  encode(message, writer = new BinaryWriter()) {
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBenchmarkRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },
  create(base) {
    return BenchmarkRequest.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseBenchmarkRequest();
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    return message;
  },
};
function createBaseBenchmarkResponse() {
  return { benchmarkResults: '', metadata: undefined };
}
export const BenchmarkResponse = {
  encode(message, writer = new BinaryWriter()) {
    if (message.benchmarkResults !== '') {
      writer.uint32(10).string(message.benchmarkResults);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(18).fork()).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBenchmarkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.benchmarkResults = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      benchmarkResults: isSet(object.benchmarkResults)
        ? globalThis.String(object.benchmarkResults)
        : '',
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.benchmarkResults !== '') {
      obj.benchmarkResults = message.benchmarkResults;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },
  create(base) {
    return BenchmarkResponse.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseBenchmarkResponse();
    message.benchmarkResults = object.benchmarkResults ?? '';
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    return message;
  },
};
function createBaseFakeEndpointRequest() {
  return { metadata: undefined };
}
export const FakeEndpointRequest = {
  encode(message, writer = new BinaryWriter()) {
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFakeEndpointRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },
  create(base) {
    return FakeEndpointRequest.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseFakeEndpointRequest();
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    return message;
  },
};
function createBaseFakeEndpointResponse() {
  return { message: '', metadata: undefined };
}
export const FakeEndpointResponse = {
  encode(message, writer = new BinaryWriter()) {
    if (message.message !== '') {
      writer.uint32(10).string(message.message);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(18).fork()).join();
    }
    return writer;
  },
  decode(input, length) {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFakeEndpointResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }
          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
  fromJSON(object) {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : '',
      metadata: isSet(object.metadata)
        ? Metadata.fromJSON(object.metadata)
        : undefined,
    };
  },
  toJSON(message) {
    const obj = {};
    if (message.message !== '') {
      obj.message = message.message;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },
  create(base) {
    return FakeEndpointResponse.fromPartial(base ?? {});
  },
  fromPartial(object) {
    const message = createBaseFakeEndpointResponse();
    message.message = object.message ?? '';
    message.metadata =
      object.metadata !== undefined && object.metadata !== null
        ? Metadata.fromPartial(object.metadata)
        : undefined;
    return message;
  },
};
export const CryptoGrpcServiceName = 'CryptoBroker.CryptoGrpc';
export class CryptoGrpcClientImpl {
  rpc;
  service;
  constructor(rpc, opts) {
    this.service = opts?.service || CryptoGrpcServiceName;
    this.rpc = rpc;
    this.HashData = this.HashData.bind(this);
    this.SignCertificate = this.SignCertificate.bind(this);
    this.EncryptData = this.EncryptData.bind(this);
    this.DecryptData = this.DecryptData.bind(this);
  }
  HashData(request) {
    const data = HashDataRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'HashData', data);
    return promise.then((data) =>
      HashDataResponse.decode(new BinaryReader(data)),
    );
  }
  SignCertificate(request) {
    const data = SignCertificateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'SignCertificate', data);
    return promise.then((data) =>
      SignCertificateResponse.decode(new BinaryReader(data)),
    );
  }
  EncryptData(request) {
    const data = EncryptDataRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'EncryptData', data);
    return promise.then((data) =>
      EncryptDataResponse.decode(new BinaryReader(data)),
    );
  }
  DecryptData(request) {
    const data = DecryptDataRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'DecryptData', data);
    return promise.then((data) =>
      DecryptDataResponse.decode(new BinaryReader(data)),
    );
  }
}
export const CryptoGrpcDevServiceName = 'CryptoBroker.CryptoGrpcDev';
export class CryptoGrpcDevClientImpl {
  rpc;
  service;
  constructor(rpc, opts) {
    this.service = opts?.service || CryptoGrpcDevServiceName;
    this.rpc = rpc;
    this.Benchmark = this.Benchmark.bind(this);
    this.FakeEndpoint = this.FakeEndpoint.bind(this);
  }
  Benchmark(request) {
    const data = BenchmarkRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'Benchmark', data);
    return promise.then((data) =>
      BenchmarkResponse.decode(new BinaryReader(data)),
    );
  }
  FakeEndpoint(request) {
    const data = FakeEndpointRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'FakeEndpoint', data);
    return promise.then((data) =>
      FakeEndpointResponse.decode(new BinaryReader(data)),
    );
  }
}
function bytesFromBase64(b64) {
  if (globalThis.Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, 'base64'));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}
function base64FromBytes(arr) {
  if (globalThis.Buffer) {
    return globalThis.Buffer.from(arr).toString('base64');
  } else {
    const bin = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(''));
  }
}
function isSet(value) {
  return value !== null && value !== undefined;
}
//# sourceMappingURL=messages.js.map
