// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.1
// source: messages.proto

/* eslint-disable */
import Long = require("long");
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "CryptoBroker";

/** Trace context for manual propagation */
export interface TraceContext {
  traceId: string;
  spanId: string;
  traceFlags: string;
  traceState: string;
  correlationId: string;
}

/** Metadata shared across all methods */
export interface Metadata {
  id: string;
  createdAt: string;
  traceContext?: TraceContext | undefined;
}

/** Message for a Benchmark Request */
export interface BenchmarkRequest {
  metadata: Metadata | undefined;
}

/** Response for a Benchmark Request */
export interface BenchmarkResponse {
  benchmarkResults: string;
  metadata: Metadata | undefined;
}

/** Message for a Hash Request */
export interface HashRequest {
  profile: string;
  input: Uint8Array;
  metadata: Metadata | undefined;
}

/** Response to a Hash Request */
export interface HashResponse {
  hashValue: string;
  hashAlgorithm: string;
  metadata: Metadata | undefined;
}

/** Message for a CSR (Certificate Signing Request) */
export interface SignRequest {
  profile: string;
  csr: string;
  caPrivateKey: string;
  caCert: string;
  metadata: Metadata | undefined;
  validNotBefore?: Long | undefined;
  validNotAfter?: Long | undefined;
  subject?: string | undefined;
  crlDistributionPoints: string[];
}

/** Response to a Sign Request */
export interface SignResponse {
  signedCertificate: string;
  metadata: Metadata | undefined;
}

/** Message for a Fake Endpoint Request */
export interface FakeEndpointRequest {
  metadata: Metadata | undefined;
}

/** Response to a Fake Endpoint Request */
export interface FakeEndpointResponse {
  message: string;
  metadata: Metadata | undefined;
}

function createBaseTraceContext(): TraceContext {
  return { traceId: "", spanId: "", traceFlags: "", traceState: "", correlationId: "" };
}

export const TraceContext: MessageFns<TraceContext> = {
  encode(message: TraceContext, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.traceId !== "") {
      writer.uint32(10).string(message.traceId);
    }
    if (message.spanId !== "") {
      writer.uint32(18).string(message.spanId);
    }
    if (message.traceFlags !== "") {
      writer.uint32(26).string(message.traceFlags);
    }
    if (message.traceState !== "") {
      writer.uint32(34).string(message.traceState);
    }
    if (message.correlationId !== "") {
      writer.uint32(42).string(message.correlationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TraceContext {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTraceContext();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.traceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.spanId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.traceFlags = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.traceState = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TraceContext {
    return {
      traceId: isSet(object.traceId) ? globalThis.String(object.traceId) : "",
      spanId: isSet(object.spanId) ? globalThis.String(object.spanId) : "",
      traceFlags: isSet(object.traceFlags) ? globalThis.String(object.traceFlags) : "",
      traceState: isSet(object.traceState) ? globalThis.String(object.traceState) : "",
      correlationId: isSet(object.correlationId) ? globalThis.String(object.correlationId) : "",
    };
  },

  toJSON(message: TraceContext): unknown {
    const obj: any = {};
    if (message.traceId !== "") {
      obj.traceId = message.traceId;
    }
    if (message.spanId !== "") {
      obj.spanId = message.spanId;
    }
    if (message.traceFlags !== "") {
      obj.traceFlags = message.traceFlags;
    }
    if (message.traceState !== "") {
      obj.traceState = message.traceState;
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TraceContext>, I>>(base?: I): TraceContext {
    return TraceContext.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TraceContext>, I>>(object: I): TraceContext {
    const message = createBaseTraceContext();
    message.traceId = object.traceId ?? "";
    message.spanId = object.spanId ?? "";
    message.traceFlags = object.traceFlags ?? "";
    message.traceState = object.traceState ?? "";
    message.correlationId = object.correlationId ?? "";
    return message;
  },
};

function createBaseMetadata(): Metadata {
  return { id: "", createdAt: "", traceContext: undefined };
}

export const Metadata: MessageFns<Metadata> = {
  encode(message: Metadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.createdAt !== "") {
      writer.uint32(18).string(message.createdAt);
    }
    if (message.traceContext !== undefined) {
      TraceContext.encode(message.traceContext, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Metadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.traceContext = TraceContext.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Metadata {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      traceContext: isSet(object.traceContext) ? TraceContext.fromJSON(object.traceContext) : undefined,
    };
  },

  toJSON(message: Metadata): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.traceContext !== undefined) {
      obj.traceContext = TraceContext.toJSON(message.traceContext);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Metadata>, I>>(base?: I): Metadata {
    return Metadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Metadata>, I>>(object: I): Metadata {
    const message = createBaseMetadata();
    message.id = object.id ?? "";
    message.createdAt = object.createdAt ?? "";
    message.traceContext = (object.traceContext !== undefined && object.traceContext !== null)
      ? TraceContext.fromPartial(object.traceContext)
      : undefined;
    return message;
  },
};

function createBaseBenchmarkRequest(): BenchmarkRequest {
  return { metadata: undefined };
}

export const BenchmarkRequest: MessageFns<BenchmarkRequest> = {
  encode(message: BenchmarkRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BenchmarkRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBenchmarkRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BenchmarkRequest {
    return { metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined };
  },

  toJSON(message: BenchmarkRequest): unknown {
    const obj: any = {};
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BenchmarkRequest>, I>>(base?: I): BenchmarkRequest {
    return BenchmarkRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BenchmarkRequest>, I>>(object: I): BenchmarkRequest {
    const message = createBaseBenchmarkRequest();
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseBenchmarkResponse(): BenchmarkResponse {
  return { benchmarkResults: "", metadata: undefined };
}

export const BenchmarkResponse: MessageFns<BenchmarkResponse> = {
  encode(message: BenchmarkResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.benchmarkResults !== "") {
      writer.uint32(10).string(message.benchmarkResults);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BenchmarkResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBenchmarkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.benchmarkResults = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BenchmarkResponse {
    return {
      benchmarkResults: isSet(object.benchmarkResults) ? globalThis.String(object.benchmarkResults) : "",
      metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined,
    };
  },

  toJSON(message: BenchmarkResponse): unknown {
    const obj: any = {};
    if (message.benchmarkResults !== "") {
      obj.benchmarkResults = message.benchmarkResults;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BenchmarkResponse>, I>>(base?: I): BenchmarkResponse {
    return BenchmarkResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BenchmarkResponse>, I>>(object: I): BenchmarkResponse {
    const message = createBaseBenchmarkResponse();
    message.benchmarkResults = object.benchmarkResults ?? "";
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseHashRequest(): HashRequest {
  return { profile: "", input: new Uint8Array(0), metadata: undefined };
}

export const HashRequest: MessageFns<HashRequest> = {
  encode(message: HashRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.profile !== "") {
      writer.uint32(10).string(message.profile);
    }
    if (message.input.length !== 0) {
      writer.uint32(18).bytes(message.input);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HashRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHashRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.profile = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HashRequest {
    return {
      profile: isSet(object.profile) ? globalThis.String(object.profile) : "",
      input: isSet(object.input) ? bytesFromBase64(object.input) : new Uint8Array(0),
      metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined,
    };
  },

  toJSON(message: HashRequest): unknown {
    const obj: any = {};
    if (message.profile !== "") {
      obj.profile = message.profile;
    }
    if (message.input.length !== 0) {
      obj.input = base64FromBytes(message.input);
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HashRequest>, I>>(base?: I): HashRequest {
    return HashRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HashRequest>, I>>(object: I): HashRequest {
    const message = createBaseHashRequest();
    message.profile = object.profile ?? "";
    message.input = object.input ?? new Uint8Array(0);
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseHashResponse(): HashResponse {
  return { hashValue: "", hashAlgorithm: "", metadata: undefined };
}

export const HashResponse: MessageFns<HashResponse> = {
  encode(message: HashResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hashValue !== "") {
      writer.uint32(10).string(message.hashValue);
    }
    if (message.hashAlgorithm !== "") {
      writer.uint32(18).string(message.hashAlgorithm);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HashResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHashResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hashValue = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.hashAlgorithm = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HashResponse {
    return {
      hashValue: isSet(object.hashValue) ? globalThis.String(object.hashValue) : "",
      hashAlgorithm: isSet(object.hashAlgorithm) ? globalThis.String(object.hashAlgorithm) : "",
      metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined,
    };
  },

  toJSON(message: HashResponse): unknown {
    const obj: any = {};
    if (message.hashValue !== "") {
      obj.hashValue = message.hashValue;
    }
    if (message.hashAlgorithm !== "") {
      obj.hashAlgorithm = message.hashAlgorithm;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HashResponse>, I>>(base?: I): HashResponse {
    return HashResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HashResponse>, I>>(object: I): HashResponse {
    const message = createBaseHashResponse();
    message.hashValue = object.hashValue ?? "";
    message.hashAlgorithm = object.hashAlgorithm ?? "";
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseSignRequest(): SignRequest {
  return {
    profile: "",
    csr: "",
    caPrivateKey: "",
    caCert: "",
    metadata: undefined,
    validNotBefore: undefined,
    validNotAfter: undefined,
    subject: undefined,
    crlDistributionPoints: [],
  };
}

export const SignRequest: MessageFns<SignRequest> = {
  encode(message: SignRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.profile !== "") {
      writer.uint32(10).string(message.profile);
    }
    if (message.csr !== "") {
      writer.uint32(18).string(message.csr);
    }
    if (message.caPrivateKey !== "") {
      writer.uint32(26).string(message.caPrivateKey);
    }
    if (message.caCert !== "") {
      writer.uint32(34).string(message.caCert);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(42).fork()).join();
    }
    if (message.validNotBefore !== undefined) {
      writer.uint32(48).uint64(message.validNotBefore.toString());
    }
    if (message.validNotAfter !== undefined) {
      writer.uint32(56).uint64(message.validNotAfter.toString());
    }
    if (message.subject !== undefined) {
      writer.uint32(66).string(message.subject);
    }
    for (const v of message.crlDistributionPoints) {
      writer.uint32(74).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.profile = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.csr = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.caPrivateKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.caCert = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.validNotBefore = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.validNotAfter = Long.fromString(reader.uint64().toString(), true);
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.crlDistributionPoints.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignRequest {
    return {
      profile: isSet(object.profile) ? globalThis.String(object.profile) : "",
      csr: isSet(object.csr) ? globalThis.String(object.csr) : "",
      caPrivateKey: isSet(object.caPrivateKey) ? globalThis.String(object.caPrivateKey) : "",
      caCert: isSet(object.caCert) ? globalThis.String(object.caCert) : "",
      metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined,
      validNotBefore: isSet(object.validNotBefore) ? Long.fromValue(object.validNotBefore) : undefined,
      validNotAfter: isSet(object.validNotAfter) ? Long.fromValue(object.validNotAfter) : undefined,
      subject: isSet(object.subject) ? globalThis.String(object.subject) : undefined,
      crlDistributionPoints: globalThis.Array.isArray(object?.crlDistributionPoints)
        ? object.crlDistributionPoints.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: SignRequest): unknown {
    const obj: any = {};
    if (message.profile !== "") {
      obj.profile = message.profile;
    }
    if (message.csr !== "") {
      obj.csr = message.csr;
    }
    if (message.caPrivateKey !== "") {
      obj.caPrivateKey = message.caPrivateKey;
    }
    if (message.caCert !== "") {
      obj.caCert = message.caCert;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    if (message.validNotBefore !== undefined) {
      obj.validNotBefore = (message.validNotBefore || Long.UZERO).toString();
    }
    if (message.validNotAfter !== undefined) {
      obj.validNotAfter = (message.validNotAfter || Long.UZERO).toString();
    }
    if (message.subject !== undefined) {
      obj.subject = message.subject;
    }
    if (message.crlDistributionPoints?.length) {
      obj.crlDistributionPoints = message.crlDistributionPoints;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignRequest>, I>>(base?: I): SignRequest {
    return SignRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignRequest>, I>>(object: I): SignRequest {
    const message = createBaseSignRequest();
    message.profile = object.profile ?? "";
    message.csr = object.csr ?? "";
    message.caPrivateKey = object.caPrivateKey ?? "";
    message.caCert = object.caCert ?? "";
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    message.validNotBefore = (object.validNotBefore !== undefined && object.validNotBefore !== null)
      ? Long.fromValue(object.validNotBefore)
      : undefined;
    message.validNotAfter = (object.validNotAfter !== undefined && object.validNotAfter !== null)
      ? Long.fromValue(object.validNotAfter)
      : undefined;
    message.subject = object.subject ?? undefined;
    message.crlDistributionPoints = object.crlDistributionPoints?.map((e) => e) || [];
    return message;
  },
};

function createBaseSignResponse(): SignResponse {
  return { signedCertificate: "", metadata: undefined };
}

export const SignResponse: MessageFns<SignResponse> = {
  encode(message: SignResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signedCertificate !== "") {
      writer.uint32(10).string(message.signedCertificate);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signedCertificate = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignResponse {
    return {
      signedCertificate: isSet(object.signedCertificate) ? globalThis.String(object.signedCertificate) : "",
      metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined,
    };
  },

  toJSON(message: SignResponse): unknown {
    const obj: any = {};
    if (message.signedCertificate !== "") {
      obj.signedCertificate = message.signedCertificate;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignResponse>, I>>(base?: I): SignResponse {
    return SignResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignResponse>, I>>(object: I): SignResponse {
    const message = createBaseSignResponse();
    message.signedCertificate = object.signedCertificate ?? "";
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseFakeEndpointRequest(): FakeEndpointRequest {
  return { metadata: undefined };
}

export const FakeEndpointRequest: MessageFns<FakeEndpointRequest> = {
  encode(message: FakeEndpointRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FakeEndpointRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFakeEndpointRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FakeEndpointRequest {
    return { metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined };
  },

  toJSON(message: FakeEndpointRequest): unknown {
    const obj: any = {};
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FakeEndpointRequest>, I>>(base?: I): FakeEndpointRequest {
    return FakeEndpointRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FakeEndpointRequest>, I>>(object: I): FakeEndpointRequest {
    const message = createBaseFakeEndpointRequest();
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

function createBaseFakeEndpointResponse(): FakeEndpointResponse {
  return { message: "", metadata: undefined };
}

export const FakeEndpointResponse: MessageFns<FakeEndpointResponse> = {
  encode(message: FakeEndpointResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.metadata !== undefined) {
      Metadata.encode(message.metadata, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FakeEndpointResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFakeEndpointResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.metadata = Metadata.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FakeEndpointResponse {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      metadata: isSet(object.metadata) ? Metadata.fromJSON(object.metadata) : undefined,
    };
  },

  toJSON(message: FakeEndpointResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.metadata !== undefined) {
      obj.metadata = Metadata.toJSON(message.metadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FakeEndpointResponse>, I>>(base?: I): FakeEndpointResponse {
    return FakeEndpointResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FakeEndpointResponse>, I>>(object: I): FakeEndpointResponse {
    const message = createBaseFakeEndpointResponse();
    message.message = object.message ?? "";
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? Metadata.fromPartial(object.metadata)
      : undefined;
    return message;
  },
};

export interface CryptoGrpc {
  Benchmark(request: BenchmarkRequest): Promise<BenchmarkResponse>;
  Hash(request: HashRequest): Promise<HashResponse>;
  Sign(request: SignRequest): Promise<SignResponse>;
  FakeEndpoint(request: FakeEndpointRequest): Promise<FakeEndpointResponse>;
}

export const CryptoGrpcServiceName = "CryptoBroker.CryptoGrpc";
export class CryptoGrpcClientImpl implements CryptoGrpc {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || CryptoGrpcServiceName;
    this.rpc = rpc;
    this.Benchmark = this.Benchmark.bind(this);
    this.Hash = this.Hash.bind(this);
    this.Sign = this.Sign.bind(this);
    this.FakeEndpoint = this.FakeEndpoint.bind(this);
  }
  Benchmark(request: BenchmarkRequest): Promise<BenchmarkResponse> {
    const data = BenchmarkRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Benchmark", data);
    return promise.then((data) => BenchmarkResponse.decode(new BinaryReader(data)));
  }

  Hash(request: HashRequest): Promise<HashResponse> {
    const data = HashRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Hash", data);
    return promise.then((data) => HashResponse.decode(new BinaryReader(data)));
  }

  Sign(request: SignRequest): Promise<SignResponse> {
    const data = SignRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Sign", data);
    return promise.then((data) => SignResponse.decode(new BinaryReader(data)));
  }

  FakeEndpoint(request: FakeEndpointRequest): Promise<FakeEndpointResponse> {
    const data = FakeEndpointRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "FakeEndpoint", data);
    return promise.then((data) => FakeEndpointResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
