name: NPM Version Bump
on:
  workflow_dispatch:
    inputs:
      version:
        # Note: use prerelease to increase the counter, release to finalize version
        description: 'Version (pre(patch/minor/major), prerelease, release)'
        default: 'prerelease'
        required: true
        type: choice
        options:
          - prepatch
          - preminor
          - premajor
          - prerelease
          - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

permissions: {}

jobs:
  bump-version:
    name: Bump Version
    permissions:
      contents: write # for pushing version bump commit and tag
    runs-on: ubuntu-latest
    environment: DEPLOYMENT

    steps:
      - name: Create GitHub app token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.DEPLOYMENT_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Run version bump
        uses: open-crypto-broker/.github/actions/npm-version-bump@main # nolint # zizmor: ignore[unpinned-uses]
        with:
          version: ${{ inputs.version }}
